
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://132.232.121.87:3306/myTable
    username: bimo
    password: qwe123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true

logging:
  level:
    root: debug
  file:
    name: log/blog.log
server:
  port: 8081

